# Generated by Django 3.0.8 on 2020-08-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(choices=[('Fairmount Line', 'CR-Fairmount'), ('Fitchburg Line', 'CR-Fitchburg'), ('Framingham/Worcester Line', 'CR-Worcester'), ('Franklin Line/Foxboro Pilot', 'CR-Franklin'), ('Greenbush Line', 'CR-Greenbush'), ('Haverhill Line', 'CR-Haverhill'), ('Kingston/Plymouth Line', 'CR-Kingston'), ('Lowell Line', 'CR-Lowell'), ('Middleborough/Lakeville Line', 'CR-Middleborough'), ('Needham Line', 'CR-Needham'), ('Newburyport/Rockport Line', 'CR-Newburyport'), ('Providence/Stoughton Line', 'CR-Providence'), ('Foxboro Event Service', 'CR-Foxboro')], max_length=100),
        ),
        migrations.CreateModel(
            name='Starting_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTime.Line')),
            ],
        ),
        migrations.CreateModel(
            name='Ending_Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTime.Line')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='ending_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTime.Ending_Stop'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='starting_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnTime.Starting_Stop'),
        ),
    ]
