# Generated by Django 3.0.8 on 2020-08-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTime', '0002_auto_20200815_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='New Trip', max_length=50),
        ),
    ]
