# Generated by Django 3.0.8 on 2020-08-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTime', '0003_trip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ending_stop',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(choices=[('Fairmount Line', 'CR-Fairmount'), ('Fitchburg Line', 'CR-Fitchburg'), ('Framingham/Worcester Line', 'CR-Worcester'), ('Franklin Line/Foxboro Pilot', 'CR-Franklin'), ('Greenbush Line', 'CR-Greenbush'), ('Haverhill Line', 'CR-Haverhill'), ('Kingston/Plymouth Line', 'CR-Kingston'), ('Lowell Line', 'CR-Lowell'), ('Middleborough/Lakeville Line', 'CR-Middleborough'), ('Needham Line', 'CR-Needham'), ('Newburyport/Rockport Line', 'CR-Newburyport'), ('Providence/Stoughton Line', 'CR-Providence'), ('Foxboro Event Service', 'CR-Foxboro')], max_length=300),
        ),
        migrations.AlterField(
            model_name='starting_stop',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
