# Generated by Django 3.0.8 on 2020-08-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnTime', '0004_auto_20200830_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='TripInput',
        ),
    ]
