# Generated by Django 3.0.8 on 2020-09-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTime', '0005_auto_20200831_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='ending_stop',
            name='index',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='starting_stop',
            name='index',
            field=models.IntegerField(default=2),
        ),
    ]
