# Generated by Django 3.0.8 on 2020-09-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTime', '0006_auto_20200902_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(choices=[('CR-Fairmount', 'Fairmount Line'), ('CR-Fitchburg', 'Fitchburg Line'), ('CR-Worcester', 'Framingham/Worcester Line'), ('CR-Franklin', 'Franklin Line/Foxboro Pilot'), ('CR-Greenbush', 'Greenbush Line'), ('CR-Haverhill', 'Haverhill Line'), ('CR-Kingston', 'Kingston/Plymouth Line'), ('CR-Lowell', 'Lowell Line'), ('CR-Middleborough', 'Middleborough/Lakeville Line'), ('CR-Needham', 'Needham Line'), ('CR-Newburyport', 'Newburyport/Rockport Line'), ('CR-Providence', 'Providence/Stoughton Line'), ('CR-Foxboro', 'Foxboro Event Service')], max_length=300),
        ),
    ]
